networks:
  dostava_network:
    driver: bridge

volumes:
  neo4j_data:
    driver: local

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: on-failure
    ports:
      - "7474:7474"  # vizuelni interfejs
      - "7687:7687"  # Flask
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

    networks:
      - dostava_network

  user-service:
    build: ./backend/user-service
    restart: on-failure
    volumes:
      - ./backend/model.py:/dostava/model.py
    ports:
      - "8080:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j
    networks:
      - dostava_network


  resource-service:
    build: ./backend/resource-service
    restart: on-failure
    volumes:
      - ./backend/model.py:/dostava/model.py
    ports:
      - "8081:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j

    networks:
      - dostava_network

  delivery-service:
    build: ./backend/delivery-service
    restart: on-failure
    volumes:
      - ./backend/model.py:/dostava/model.py
    ports:
      - "8082:8080"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USERNAME=neo4j
      - NEO4J_PASSWORD=password
    depends_on:
      - neo4j

    networks:
      - dostava_network

  gateway:
    build: ./backend/gateway
    restart: on-failure
    ports:
      - "8083:8080"
    depends_on:
      - user-service
      - resource-service
      - delivery-service
    networks:
      - dostava_network

