volumes:
  neo4j_data:
    driver: local
  influxdb2-data:
    driver: local
  redis-data:
    driver: local

services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    restart: on-failure
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - neo4j_data:/data

  influxdb2:
    image: influxdb:2.7.6
    ports:
      - '8086:8086'
    volumes:
      - influxdb2-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=superpassword
      - DOCKER_INFLUXDB_INIT_ORG=docs
      - DOCKER_INFLUXDB_INIT_BUCKET=home
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=mytoken123

  redisdb:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redisdb
    environment:
      - REDIS_HOST=redisdb
      - REDIS_PORT=6379

  auth-service:
    build: ./application/auth-service/
    restart: on-failure
    command: flask run --host=0.0.0.0 --port=8080
    depends_on:
      - neo4j
    develop:
      watch:
        - action: sync
          path: ./application/auth-service
          target: /app
          ignore:
            - "**/.*"

  delivery-subsystem:
    build: ./application/delivery-subsystem/
    restart: on-failure
    command: flask run --host=0.0.0.0 --port=8080
    depends_on:
      - neo4j
      - influxdb2
      - redisdb
    develop:
      watch:
        - action: sync
          path: ./application/delivery-subsystem
          target: /app
          ignore:
            - "**/.*"

  gateway:
    build: ./gateway
    restart: on-failure
    volumes:
      - ./application/auth-service:/auth-app
      - ./application/delivery-subsystem:/delivery-app
    ports:
      - "8000:8080"
    environment:
      # VRAĆENE KLJUČNE VARIJABLE
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - AUTH_SERVICE_URL=http://auth-service:8080
      - DELIVERY_SUBSYSTEM_URL=http://delivery-subsystem:8080
    command: flask run --host=0.0.0.0 --port=8080
    depends_on:
      - delivery-subsystem
      - auth-service
    develop:
      watch:
        - action: sync
          path: ./gateway
          target: /app
          ignore:
            - "**/.*"
        