@startuml
hide circle


package "ADMINISTRATOR" {

class Korisnik {
  + korisnik_id : int <<PK>>
  --
  ime : string
  prezime : string
  email : string
  lozinka : string
  telefon : string
  status_naloga : string
}

class Administrator {
  + korisnik_id: int <<PK,FK>>
}


}


package "DOSTAVA" {

class MenadzerDostave {
  + korisnik_id: int <<PK,FK>>
}

class Dostavljac {
  + korisnik_id : int <<PK,FK>>
  + vozilo_id : int <<FK>>
  --
  motor_dozvola : boolean
  auto_dozvola : boolean
  plata : decimal
  prosecna_ocena : decimal
  aktivan : bool
}


class SimulatorPozicije {
  + dostavljac_id : int <<FK>>
  --
  geo_sirina : decimal
  geo_duzina : decimal
}



class Vozilo {
  + vozilo_id : int <<PK>>
  + vlasnik_id : int <<FK>>
  --
  tip : string
  model : string
  marka : string
  registarska_oznaka : string
  boja : string
  spreman : boolean
  u_upotrebi : boolean
  opis : string
  
}




class Dostava {
  + dostava_id : int <<PK>>
  + dostavljac_id : int <<FK>>
  --
  status : string
  od_lokacije : string
  do_lokacije : string
  vreme_porucivanja : datetime
  vreme_pocetka : datetime
  vreme_preuzimanja : datetime
  vreme_dostavljanja : datetime
  ocena : int
  
}

}


package "NARUCIVANJE" {

class Narucilac {
  + korisnik_id : int <<PK, FK>>
  --
  adresa_dostave : string
}



class Porudzbina {
  + porudzbina_id : int <<PK>>
  + narucilac_id : int <<FK>>
  + restoran_id : int <<FK>>
  + dostava_id : int <<FK>>
  --
  status_id : int
  vrijeme_narucivanja : datetime
  procijenjeno_vrijeme_pripreme : int
  vrijeme_spremnosti : datetime
  adresa_dostave : string
  napomena_korisnika : string
  ukupna_cijena_artikala : decimal
  cijena_dostave : decimal
  razlog_odbijanja : string
}

class StavkaPorudzbine {
  + stavka_id : int <<PK>>
  + porudzbina_id : int <<FK>>
  + artikal_id : int <<FK>>
  --
  kolicina : int
  cijena_po_komadu : decimal
  napomena : string
}

class AnalizaZarade {
  + analiza_id : int <<PK>>
  + restoran_id : int <<FK>>
  --
  datum_od : date
  datum_do : date
  broj_porudzbina : int
  ukupna_zarada : decimal
  zarada_od_specijalnih_ponuda : decimal
  zarada_od_preporuka : decimal
}


}


package "RESTORAN" {

class MenadzerRestorana {
  + korisnik_id : int <<PK, FK>>
  + restoran_id : int <<FK>>
}

class ZaposleniRestorana {
  + korisnik_id : int <<PK, FK>>
  + restoran_id : int <<FK>>
}




class Restoran {
  + restoran_id : int <<PK>>
  --
  naziv : string
  adresa : string
  kontakt_telefon : string
  email : string
  opis : string
  radno_vrijeme : string
  prima_porudzbine : boolean
  razlog_nedostupnosti : string
  status_restorana : string
}

class KategorijaArtikla {
  + kategorija_id : int <<PK>>
  + restoran_id : int <<FK>>
  --
  naziv_kategorije : string
  opis : string
}

class Artikal {
  + artikal_id : int <<PK>>
  + restoran_id : int <<FK>>
  + kategorija_id : int <<FK>>
  --
  naziv : string
  opis : string
  cijena : decimal
  slika : string
  dostupan : boolean
}

class SpecijalnaPonuda {
  + ponuda_id : int <<PK>>
  + restoran_id : int <<FK>>
  + artikal_id : int <<FK>>
  --
  naziv : string
  opis : string
  procenat_popusta : decimal
  aktivna : boolean
}





class PreporukaRestorana {
  + preporuka_id : int <<PK>>
  + restoran_id : int <<FK>>
  --
  datum : date
  pozicija : int
  broj_prikaza : int
  broj_klikova : int
  broj_porudzbina : int
  zarada_preko_preporuka : decimal
}
}



Korisnik <|-- Administrator
Korisnik <|-- Dostavljac
Korisnik <|-- MenadzerDostave
Dostavljac "1" -- "1" SimulatorPozicije : "prati se"

Vozilo "0..1" -- "0..1" Dostavljac : "duži"
Vozilo "0..1" -- "0..1" Dostavljac : "poseduje"

Korisnik <|-- Narucilac

Porudzbina "1" -- "1" Dostava : "ima"
Dostavljac "1" -- "0..*" Dostava : "dostavlja"
Korisnik <|-- MenadzerRestorana
Korisnik <|-- ZaposleniRestorana

Restoran "1" -- "0..*" MenadzerRestorana : ima
Restoran "1" -- "0..*" ZaposleniRestorana : ima
Restoran "1" -- "0..*" KategorijaArtikla : ima
Restoran "1" -- "0..*" Artikal : nudi

KategorijaArtikla "1" -- "0..*" Artikal : sadrzi

Restoran "1" -- "0..*" SpecijalnaPonuda : kreira
Artikal "0..1" -- "0..*" SpecijalnaPonuda : ima

Narucilac "1" -- "0..*" Porudzbina : kreira
Restoran "1" -- "0..*" Porudzbina : prima
ZaposleniRestorana "0..1" -- "0..*" Porudzbina : obradjuje
Porudzbina "1" -- "1..*" StavkaPorudzbine : sadrzi
Artikal "1" -- "0..*" StavkaPorudzbine : nalazi_se_u

Restoran "1" -- "0..*" PreporukaRestorana : ima
Restoran "1" -- "0..*" AnalizaZarade : ima
@enduml