// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class ItemAPI implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject itemAPIMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.ItemAPI";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ItemId("ItemId"),
		Name("Name"),
		description("description"),
		category("category"),
		available("available"),
		imageUrl("imageUrl"),
		price("price"),
		ItemAPI_RestaurantAPI("MyFirstModule.ItemAPI_RestaurantAPI"),
		ItemAPI_Order("MyFirstModule.ItemAPI_Order"),
		FoodPhoto_ItemAPI("MyFirstModule.FoodPhoto_ItemAPI"),
		ItemAPI_OrderItem("MyFirstModule.ItemAPI_OrderItem");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ItemAPI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ItemAPI(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject itemAPIMendixObject)
	{
		if (itemAPIMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!itemAPIMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.itemAPIMendixObject = itemAPIMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.ItemAPI initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.ItemAPI(context, mendixObject);
	}

	public static myfirstmodule.proxies.ItemAPI load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.ItemAPI.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.ItemAPI> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.ItemAPI.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ItemId
	 */
	public final java.lang.Integer getItemId()
	{
		return getItemId(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemId
	 */
	public final java.lang.Integer getItemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ItemId.toString());
	}

	/**
	 * Set value of ItemId
	 * @param itemid
	 */
	public final void setItemId(java.lang.Integer itemid)
	{
		setItemId(getContext(), itemid);
	}

	/**
	 * Set value of ItemId
	 * @param context
	 * @param itemid
	 */
	public final void setItemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer itemid)
	{
		getMendixObject().setValue(context, MemberNames.ItemId.toString(), itemid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of description
	 */
	public final java.lang.String getdescription()
	{
		return getdescription(getContext());
	}

	/**
	 * @param context
	 * @return value of description
	 */
	public final java.lang.String getdescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.description.toString());
	}

	/**
	 * Set value of description
	 * @param description
	 */
	public final void setdescription(java.lang.String description)
	{
		setdescription(getContext(), description);
	}

	/**
	 * Set value of description
	 * @param context
	 * @param description
	 */
	public final void setdescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.description.toString(), description);
	}

	/**
	 * @return value of category
	 */
	public final java.lang.String getcategory()
	{
		return getcategory(getContext());
	}

	/**
	 * @param context
	 * @return value of category
	 */
	public final java.lang.String getcategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.category.toString());
	}

	/**
	 * Set value of category
	 * @param category
	 */
	public final void setcategory(java.lang.String category)
	{
		setcategory(getContext(), category);
	}

	/**
	 * Set value of category
	 * @param context
	 * @param category
	 */
	public final void setcategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.category.toString(), category);
	}

	/**
	 * @return value of available
	 */
	public final java.lang.Boolean getavailable()
	{
		return getavailable(getContext());
	}

	/**
	 * @param context
	 * @return value of available
	 */
	public final java.lang.Boolean getavailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.available.toString());
	}

	/**
	 * Set value of available
	 * @param available
	 */
	public final void setavailable(java.lang.Boolean available)
	{
		setavailable(getContext(), available);
	}

	/**
	 * Set value of available
	 * @param context
	 * @param available
	 */
	public final void setavailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean available)
	{
		getMendixObject().setValue(context, MemberNames.available.toString(), available);
	}

	/**
	 * @return value of imageUrl
	 */
	public final java.lang.String getimageUrl()
	{
		return getimageUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of imageUrl
	 */
	public final java.lang.String getimageUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.imageUrl.toString());
	}

	/**
	 * Set value of imageUrl
	 * @param imageurl
	 */
	public final void setimageUrl(java.lang.String imageurl)
	{
		setimageUrl(getContext(), imageurl);
	}

	/**
	 * Set value of imageUrl
	 * @param context
	 * @param imageurl
	 */
	public final void setimageUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imageurl)
	{
		getMendixObject().setValue(context, MemberNames.imageUrl.toString(), imageurl);
	}

	/**
	 * @return value of price
	 */
	public final java.math.BigDecimal getprice()
	{
		return getprice(getContext());
	}

	/**
	 * @param context
	 * @return value of price
	 */
	public final java.math.BigDecimal getprice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.price.toString());
	}

	/**
	 * Set value of price
	 * @param price
	 */
	public final void setprice(java.math.BigDecimal price)
	{
		setprice(getContext(), price);
	}

	/**
	 * Set value of price
	 * @param context
	 * @param price
	 */
	public final void setprice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.price.toString(), price);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ItemAPI_RestaurantAPI
	 */
	public final myfirstmodule.proxies.RestaurantAPI getItemAPI_RestaurantAPI() throws com.mendix.core.CoreException
	{
		return getItemAPI_RestaurantAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemAPI_RestaurantAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RestaurantAPI getItemAPI_RestaurantAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RestaurantAPI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ItemAPI_RestaurantAPI.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RestaurantAPI.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ItemAPI_RestaurantAPI
	 * @param itemapi_restaurantapi
	 */
	public final void setItemAPI_RestaurantAPI(myfirstmodule.proxies.RestaurantAPI itemapi_restaurantapi)
	{
		setItemAPI_RestaurantAPI(getContext(), itemapi_restaurantapi);
	}

	/**
	 * Set value of ItemAPI_RestaurantAPI
	 * @param context
	 * @param itemapi_restaurantapi
	 */
	public final void setItemAPI_RestaurantAPI(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RestaurantAPI itemapi_restaurantapi)
	{
		if (itemapi_restaurantapi == null) {
			getMendixObject().setValue(context, MemberNames.ItemAPI_RestaurantAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ItemAPI_RestaurantAPI.toString(), itemapi_restaurantapi.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ItemAPI_Order
	 */
	public final myfirstmodule.proxies.Order getItemAPI_Order() throws com.mendix.core.CoreException
	{
		return getItemAPI_Order(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemAPI_Order
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Order getItemAPI_Order(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Order result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ItemAPI_Order.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Order.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ItemAPI_Order
	 * @param itemapi_order
	 */
	public final void setItemAPI_Order(myfirstmodule.proxies.Order itemapi_order)
	{
		setItemAPI_Order(getContext(), itemapi_order);
	}

	/**
	 * Set value of ItemAPI_Order
	 * @param context
	 * @param itemapi_order
	 */
	public final void setItemAPI_Order(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Order itemapi_order)
	{
		if (itemapi_order == null) {
			getMendixObject().setValue(context, MemberNames.ItemAPI_Order.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ItemAPI_Order.toString(), itemapi_order.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FoodPhoto_ItemAPI
	 */
	public final myfirstmodule.proxies.FoodPhoto getFoodPhoto_ItemAPI() throws com.mendix.core.CoreException
	{
		return getFoodPhoto_ItemAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of FoodPhoto_ItemAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.FoodPhoto getFoodPhoto_ItemAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.FoodPhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FoodPhoto_ItemAPI.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.FoodPhoto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FoodPhoto_ItemAPI
	 * @param foodphoto_itemapi
	 */
	public final void setFoodPhoto_ItemAPI(myfirstmodule.proxies.FoodPhoto foodphoto_itemapi)
	{
		setFoodPhoto_ItemAPI(getContext(), foodphoto_itemapi);
	}

	/**
	 * Set value of FoodPhoto_ItemAPI
	 * @param context
	 * @param foodphoto_itemapi
	 */
	public final void setFoodPhoto_ItemAPI(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.FoodPhoto foodphoto_itemapi)
	{
		if (foodphoto_itemapi == null) {
			getMendixObject().setValue(context, MemberNames.FoodPhoto_ItemAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FoodPhoto_ItemAPI.toString(), foodphoto_itemapi.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ItemAPI_OrderItem
	 */
	public final myfirstmodule.proxies.OrderItem getItemAPI_OrderItem() throws com.mendix.core.CoreException
	{
		return getItemAPI_OrderItem(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemAPI_OrderItem
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.OrderItem getItemAPI_OrderItem(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.OrderItem result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ItemAPI_OrderItem.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.OrderItem.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ItemAPI_OrderItem
	 * @param itemapi_orderitem
	 */
	public final void setItemAPI_OrderItem(myfirstmodule.proxies.OrderItem itemapi_orderitem)
	{
		setItemAPI_OrderItem(getContext(), itemapi_orderitem);
	}

	/**
	 * Set value of ItemAPI_OrderItem
	 * @param context
	 * @param itemapi_orderitem
	 */
	public final void setItemAPI_OrderItem(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.OrderItem itemapi_orderitem)
	{
		if (itemapi_orderitem == null) {
			getMendixObject().setValue(context, MemberNames.ItemAPI_OrderItem.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ItemAPI_OrderItem.toString(), itemapi_orderitem.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return itemAPIMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.ItemAPI that = (myfirstmodule.proxies.ItemAPI) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
