// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Item implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject itemMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Item";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ItemId("ItemId"),
		Name("Name"),
		description("description"),
		category("category"),
		available("available"),
		imageUrl("imageUrl"),
		price("price"),
		Item_JsonObject("MyFirstModule.Item_JsonObject");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Item(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Item(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject itemMendixObject)
	{
		if (itemMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!itemMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.itemMendixObject = itemMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Item initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Item(context, mendixObject);
	}

	public static myfirstmodule.proxies.Item load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Item.initialize(context, mendixObject);
	}

	/**
	 * @return value of ItemId
	 */
	public final java.lang.Integer getItemId()
	{
		return getItemId(getContext());
	}

	/**
	 * @param context
	 * @return value of ItemId
	 */
	public final java.lang.Integer getItemId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ItemId.toString());
	}

	/**
	 * Set value of ItemId
	 * @param itemid
	 */
	public final void setItemId(java.lang.Integer itemid)
	{
		setItemId(getContext(), itemid);
	}

	/**
	 * Set value of ItemId
	 * @param context
	 * @param itemid
	 */
	public final void setItemId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer itemid)
	{
		getMendixObject().setValue(context, MemberNames.ItemId.toString(), itemid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of description
	 */
	public final java.lang.String getdescription()
	{
		return getdescription(getContext());
	}

	/**
	 * @param context
	 * @return value of description
	 */
	public final java.lang.String getdescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.description.toString());
	}

	/**
	 * Set value of description
	 * @param description
	 */
	public final void setdescription(java.lang.String description)
	{
		setdescription(getContext(), description);
	}

	/**
	 * Set value of description
	 * @param context
	 * @param description
	 */
	public final void setdescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.description.toString(), description);
	}

	/**
	 * @return value of category
	 */
	public final java.lang.String getcategory()
	{
		return getcategory(getContext());
	}

	/**
	 * @param context
	 * @return value of category
	 */
	public final java.lang.String getcategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.category.toString());
	}

	/**
	 * Set value of category
	 * @param category
	 */
	public final void setcategory(java.lang.String category)
	{
		setcategory(getContext(), category);
	}

	/**
	 * Set value of category
	 * @param context
	 * @param category
	 */
	public final void setcategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.category.toString(), category);
	}

	/**
	 * @return value of available
	 */
	public final java.lang.Boolean getavailable()
	{
		return getavailable(getContext());
	}

	/**
	 * @param context
	 * @return value of available
	 */
	public final java.lang.Boolean getavailable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.available.toString());
	}

	/**
	 * Set value of available
	 * @param available
	 */
	public final void setavailable(java.lang.Boolean available)
	{
		setavailable(getContext(), available);
	}

	/**
	 * Set value of available
	 * @param context
	 * @param available
	 */
	public final void setavailable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean available)
	{
		getMendixObject().setValue(context, MemberNames.available.toString(), available);
	}

	/**
	 * @return value of imageUrl
	 */
	public final java.lang.String getimageUrl()
	{
		return getimageUrl(getContext());
	}

	/**
	 * @param context
	 * @return value of imageUrl
	 */
	public final java.lang.String getimageUrl(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.imageUrl.toString());
	}

	/**
	 * Set value of imageUrl
	 * @param imageurl
	 */
	public final void setimageUrl(java.lang.String imageurl)
	{
		setimageUrl(getContext(), imageurl);
	}

	/**
	 * Set value of imageUrl
	 * @param context
	 * @param imageurl
	 */
	public final void setimageUrl(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imageurl)
	{
		getMendixObject().setValue(context, MemberNames.imageUrl.toString(), imageurl);
	}

	/**
	 * @return value of price
	 */
	public final java.math.BigDecimal getprice()
	{
		return getprice(getContext());
	}

	/**
	 * @param context
	 * @return value of price
	 */
	public final java.math.BigDecimal getprice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.price.toString());
	}

	/**
	 * Set value of price
	 * @param price
	 */
	public final void setprice(java.math.BigDecimal price)
	{
		setprice(getContext(), price);
	}

	/**
	 * Set value of price
	 * @param context
	 * @param price
	 */
	public final void setprice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.price.toString(), price);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Item_JsonObject
	 */
	public final myfirstmodule.proxies.JsonObject getItem_JsonObject() throws com.mendix.core.CoreException
	{
		return getItem_JsonObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Item_JsonObject
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.JsonObject getItem_JsonObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.JsonObject result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Item_JsonObject.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.JsonObject.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Item_JsonObject
	 * @param item_jsonobject
	 */
	public final void setItem_JsonObject(myfirstmodule.proxies.JsonObject item_jsonobject)
	{
		setItem_JsonObject(getContext(), item_jsonobject);
	}

	/**
	 * Set value of Item_JsonObject
	 * @param context
	 * @param item_jsonobject
	 */
	public final void setItem_JsonObject(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.JsonObject item_jsonobject)
	{
		if (item_jsonobject == null) {
			getMendixObject().setValue(context, MemberNames.Item_JsonObject.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Item_JsonObject.toString(), item_jsonobject.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return itemMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Item that = (myfirstmodule.proxies.Item) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
