// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class JsonObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.JsonObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RestaurantId("RestaurantId"),
		Name("Name"),
		Address("Address"),
		Phone("Phone"),
		Email("Email"),
		Description("Description"),
		WorkingHours("WorkingHours"),
		AcceptsOrders("AcceptsOrders"),
		UnavailableReason("UnavailableReason"),
		Category("Category"),
		Rating("Rating"),
		Status("Status"),
		recommendationScore("recommendationScore"),
		isRecommended("isRecommended"),
		recommendationReason("recommendationReason"),
		JsonObject_Root("MyFirstModule.JsonObject_Root");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JsonObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected JsonObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jsonObjectMendixObject)
	{
		if (jsonObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!jsonObjectMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.jsonObjectMendixObject = jsonObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.JsonObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.JsonObject(context, mendixObject);
	}

	public static myfirstmodule.proxies.JsonObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.JsonObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of RestaurantId
	 */
	public final java.lang.String getRestaurantId()
	{
		return getRestaurantId(getContext());
	}

	/**
	 * @param context
	 * @return value of RestaurantId
	 */
	public final java.lang.String getRestaurantId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RestaurantId.toString());
	}

	/**
	 * Set value of RestaurantId
	 * @param restaurantid
	 */
	public final void setRestaurantId(java.lang.String restaurantid)
	{
		setRestaurantId(getContext(), restaurantid);
	}

	/**
	 * Set value of RestaurantId
	 * @param context
	 * @param restaurantid
	 */
	public final void setRestaurantId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String restaurantid)
	{
		getMendixObject().setValue(context, MemberNames.RestaurantId.toString(), restaurantid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of Phone
	 */
	public final java.lang.String getPhone()
	{
		return getPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of Phone
	 */
	public final java.lang.String getPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Phone.toString());
	}

	/**
	 * Set value of Phone
	 * @param phone
	 */
	public final void setPhone(java.lang.String phone)
	{
		setPhone(getContext(), phone);
	}

	/**
	 * Set value of Phone
	 * @param context
	 * @param phone
	 */
	public final void setPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.Phone.toString(), phone);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of WorkingHours
	 */
	public final java.lang.String getWorkingHours()
	{
		return getWorkingHours(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkingHours
	 */
	public final java.lang.String getWorkingHours(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkingHours.toString());
	}

	/**
	 * Set value of WorkingHours
	 * @param workinghours
	 */
	public final void setWorkingHours(java.lang.String workinghours)
	{
		setWorkingHours(getContext(), workinghours);
	}

	/**
	 * Set value of WorkingHours
	 * @param context
	 * @param workinghours
	 */
	public final void setWorkingHours(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workinghours)
	{
		getMendixObject().setValue(context, MemberNames.WorkingHours.toString(), workinghours);
	}

	/**
	 * @return value of AcceptsOrders
	 */
	public final java.lang.Boolean getAcceptsOrders()
	{
		return getAcceptsOrders(getContext());
	}

	/**
	 * @param context
	 * @return value of AcceptsOrders
	 */
	public final java.lang.Boolean getAcceptsOrders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AcceptsOrders.toString());
	}

	/**
	 * Set value of AcceptsOrders
	 * @param acceptsorders
	 */
	public final void setAcceptsOrders(java.lang.Boolean acceptsorders)
	{
		setAcceptsOrders(getContext(), acceptsorders);
	}

	/**
	 * Set value of AcceptsOrders
	 * @param context
	 * @param acceptsorders
	 */
	public final void setAcceptsOrders(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean acceptsorders)
	{
		getMendixObject().setValue(context, MemberNames.AcceptsOrders.toString(), acceptsorders);
	}

	/**
	 * @return value of UnavailableReason
	 */
	public final java.lang.String getUnavailableReason()
	{
		return getUnavailableReason(getContext());
	}

	/**
	 * @param context
	 * @return value of UnavailableReason
	 */
	public final java.lang.String getUnavailableReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UnavailableReason.toString());
	}

	/**
	 * Set value of UnavailableReason
	 * @param unavailablereason
	 */
	public final void setUnavailableReason(java.lang.String unavailablereason)
	{
		setUnavailableReason(getContext(), unavailablereason);
	}

	/**
	 * Set value of UnavailableReason
	 * @param context
	 * @param unavailablereason
	 */
	public final void setUnavailableReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unavailablereason)
	{
		getMendixObject().setValue(context, MemberNames.UnavailableReason.toString(), unavailablereason);
	}

	/**
	 * @return value of Category
	 */
	public final java.lang.String getCategory()
	{
		return getCategory(getContext());
	}

	/**
	 * @param context
	 * @return value of Category
	 */
	public final java.lang.String getCategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Category.toString());
	}

	/**
	 * Set value of Category
	 * @param category
	 */
	public final void setCategory(java.lang.String category)
	{
		setCategory(getContext(), category);
	}

	/**
	 * Set value of Category
	 * @param context
	 * @param category
	 */
	public final void setCategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.Category.toString(), category);
	}

	/**
	 * @return value of Rating
	 */
	public final java.math.BigDecimal getRating()
	{
		return getRating(getContext());
	}

	/**
	 * @param context
	 * @return value of Rating
	 */
	public final java.math.BigDecimal getRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Rating.toString());
	}

	/**
	 * Set value of Rating
	 * @param rating
	 */
	public final void setRating(java.math.BigDecimal rating)
	{
		setRating(getContext(), rating);
	}

	/**
	 * Set value of Rating
	 * @param context
	 * @param rating
	 */
	public final void setRating(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rating)
	{
		getMendixObject().setValue(context, MemberNames.Rating.toString(), rating);
	}

	/**
	 * @return value of Status
	 */
	public final java.lang.String getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final java.lang.String getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Status.toString());
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(java.lang.String status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.Status.toString(), status);
	}

	/**
	 * @return value of recommendationScore
	 */
	public final java.math.BigDecimal getrecommendationScore()
	{
		return getrecommendationScore(getContext());
	}

	/**
	 * @param context
	 * @return value of recommendationScore
	 */
	public final java.math.BigDecimal getrecommendationScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.recommendationScore.toString());
	}

	/**
	 * Set value of recommendationScore
	 * @param recommendationscore
	 */
	public final void setrecommendationScore(java.math.BigDecimal recommendationscore)
	{
		setrecommendationScore(getContext(), recommendationscore);
	}

	/**
	 * Set value of recommendationScore
	 * @param context
	 * @param recommendationscore
	 */
	public final void setrecommendationScore(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal recommendationscore)
	{
		getMendixObject().setValue(context, MemberNames.recommendationScore.toString(), recommendationscore);
	}

	/**
	 * @return value of isRecommended
	 */
	public final java.lang.Boolean getisRecommended()
	{
		return getisRecommended(getContext());
	}

	/**
	 * @param context
	 * @return value of isRecommended
	 */
	public final java.lang.Boolean getisRecommended(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isRecommended.toString());
	}

	/**
	 * Set value of isRecommended
	 * @param isrecommended
	 */
	public final void setisRecommended(java.lang.Boolean isrecommended)
	{
		setisRecommended(getContext(), isrecommended);
	}

	/**
	 * Set value of isRecommended
	 * @param context
	 * @param isrecommended
	 */
	public final void setisRecommended(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isrecommended)
	{
		getMendixObject().setValue(context, MemberNames.isRecommended.toString(), isrecommended);
	}

	/**
	 * @return value of recommendationReason
	 */
	public final java.lang.String getrecommendationReason()
	{
		return getrecommendationReason(getContext());
	}

	/**
	 * @param context
	 * @return value of recommendationReason
	 */
	public final java.lang.String getrecommendationReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.recommendationReason.toString());
	}

	/**
	 * Set value of recommendationReason
	 * @param recommendationreason
	 */
	public final void setrecommendationReason(java.lang.String recommendationreason)
	{
		setrecommendationReason(getContext(), recommendationreason);
	}

	/**
	 * Set value of recommendationReason
	 * @param context
	 * @param recommendationreason
	 */
	public final void setrecommendationReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recommendationreason)
	{
		getMendixObject().setValue(context, MemberNames.recommendationReason.toString(), recommendationreason);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of JsonObject_Root
	 */
	public final myfirstmodule.proxies.Root getJsonObject_Root() throws com.mendix.core.CoreException
	{
		return getJsonObject_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of JsonObject_Root
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.Root getJsonObject_Root(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.Root result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.JsonObject_Root.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.Root.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of JsonObject_Root
	 * @param jsonobject_root
	 */
	public final void setJsonObject_Root(myfirstmodule.proxies.Root jsonobject_root)
	{
		setJsonObject_Root(getContext(), jsonobject_root);
	}

	/**
	 * Set value of JsonObject_Root
	 * @param context
	 * @param jsonobject_root
	 */
	public final void setJsonObject_Root(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.Root jsonobject_root)
	{
		if (jsonobject_root == null) {
			getMendixObject().setValue(context, MemberNames.JsonObject_Root.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.JsonObject_Root.toString(), jsonobject_root.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jsonObjectMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.JsonObject that = (myfirstmodule.proxies.JsonObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
