// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class Order implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.Order";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		OrderDate("OrderDate"),
		TotalPrice("TotalPrice"),
		DeliveryPrice("DeliveryPrice"),
		EstimatedTime("EstimatedTime"),
		Status("Status"),
		Distance("Distance"),
		DriverAvailability("DriverAvailability"),
		DeliveryPeriod("DeliveryPeriod"),
		PaymentMethod("PaymentMethod"),
		Order_User("MyFirstModule.Order_User"),
		Order_RestaurantAPI("MyFirstModule.Order_RestaurantAPI");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Order(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Order(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject orderMendixObject)
	{
		if (orderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!orderMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.orderMendixObject = orderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.Order initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.Order(context, mendixObject);
	}

	public static myfirstmodule.proxies.Order load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.Order.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.Order> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.Order.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice()
	{
		return getTotalPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalPrice
	 */
	public final java.math.BigDecimal getTotalPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalPrice.toString());
	}

	/**
	 * Set value of TotalPrice
	 * @param totalprice
	 */
	public final void setTotalPrice(java.math.BigDecimal totalprice)
	{
		setTotalPrice(getContext(), totalprice);
	}

	/**
	 * Set value of TotalPrice
	 * @param context
	 * @param totalprice
	 */
	public final void setTotalPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalprice)
	{
		getMendixObject().setValue(context, MemberNames.TotalPrice.toString(), totalprice);
	}

	/**
	 * @return value of DeliveryPrice
	 */
	public final java.math.BigDecimal getDeliveryPrice()
	{
		return getDeliveryPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliveryPrice
	 */
	public final java.math.BigDecimal getDeliveryPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DeliveryPrice.toString());
	}

	/**
	 * Set value of DeliveryPrice
	 * @param deliveryprice
	 */
	public final void setDeliveryPrice(java.math.BigDecimal deliveryprice)
	{
		setDeliveryPrice(getContext(), deliveryprice);
	}

	/**
	 * Set value of DeliveryPrice
	 * @param context
	 * @param deliveryprice
	 */
	public final void setDeliveryPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal deliveryprice)
	{
		getMendixObject().setValue(context, MemberNames.DeliveryPrice.toString(), deliveryprice);
	}

	/**
	 * @return value of EstimatedTime
	 */
	public final java.lang.Integer getEstimatedTime()
	{
		return getEstimatedTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EstimatedTime
	 */
	public final java.lang.Integer getEstimatedTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EstimatedTime.toString());
	}

	/**
	 * Set value of EstimatedTime
	 * @param estimatedtime
	 */
	public final void setEstimatedTime(java.lang.Integer estimatedtime)
	{
		setEstimatedTime(getContext(), estimatedtime);
	}

	/**
	 * Set value of EstimatedTime
	 * @param context
	 * @param estimatedtime
	 */
	public final void setEstimatedTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer estimatedtime)
	{
		getMendixObject().setValue(context, MemberNames.EstimatedTime.toString(), estimatedtime);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final myfirstmodule.proxies.OrderStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final myfirstmodule.proxies.OrderStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.OrderStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(myfirstmodule.proxies.OrderStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.OrderStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of Distance
	 */
	public final java.math.BigDecimal getDistance()
	{
		return getDistance(getContext());
	}

	/**
	 * @param context
	 * @return value of Distance
	 */
	public final java.math.BigDecimal getDistance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Distance.toString());
	}

	/**
	 * Set value of Distance
	 * @param distance
	 */
	public final void setDistance(java.math.BigDecimal distance)
	{
		setDistance(getContext(), distance);
	}

	/**
	 * Set value of Distance
	 * @param context
	 * @param distance
	 */
	public final void setDistance(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal distance)
	{
		getMendixObject().setValue(context, MemberNames.Distance.toString(), distance);
	}

	/**
	 * @return value of DriverAvailability
	 */
	public final java.lang.String getDriverAvailability()
	{
		return getDriverAvailability(getContext());
	}

	/**
	 * @param context
	 * @return value of DriverAvailability
	 */
	public final java.lang.String getDriverAvailability(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DriverAvailability.toString());
	}

	/**
	 * Set value of DriverAvailability
	 * @param driveravailability
	 */
	public final void setDriverAvailability(java.lang.String driveravailability)
	{
		setDriverAvailability(getContext(), driveravailability);
	}

	/**
	 * Set value of DriverAvailability
	 * @param context
	 * @param driveravailability
	 */
	public final void setDriverAvailability(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String driveravailability)
	{
		getMendixObject().setValue(context, MemberNames.DriverAvailability.toString(), driveravailability);
	}

	/**
	 * @return value of DeliveryPeriod
	 */
	public final java.lang.String getDeliveryPeriod()
	{
		return getDeliveryPeriod(getContext());
	}

	/**
	 * @param context
	 * @return value of DeliveryPeriod
	 */
	public final java.lang.String getDeliveryPeriod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DeliveryPeriod.toString());
	}

	/**
	 * Set value of DeliveryPeriod
	 * @param deliveryperiod
	 */
	public final void setDeliveryPeriod(java.lang.String deliveryperiod)
	{
		setDeliveryPeriod(getContext(), deliveryperiod);
	}

	/**
	 * Set value of DeliveryPeriod
	 * @param context
	 * @param deliveryperiod
	 */
	public final void setDeliveryPeriod(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deliveryperiod)
	{
		getMendixObject().setValue(context, MemberNames.DeliveryPeriod.toString(), deliveryperiod);
	}

	/**
	 * Get value of PaymentMethod
	 * @param paymentmethod
	 */
	public final myfirstmodule.proxies.PaymentMethod getPaymentMethod()
	{
		return getPaymentMethod(getContext());
	}

	/**
	 * @param context
	 * @return value of PaymentMethod
	 */
	public final myfirstmodule.proxies.PaymentMethod getPaymentMethod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PaymentMethod.toString());
		if (obj == null) {
			return null;
		}
		return myfirstmodule.proxies.PaymentMethod.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PaymentMethod
	 * @param paymentmethod
	 */
	public final void setPaymentMethod(myfirstmodule.proxies.PaymentMethod paymentmethod)
	{
		setPaymentMethod(getContext(), paymentmethod);
	}

	/**
	 * Set value of PaymentMethod
	 * @param context
	 * @param paymentmethod
	 */
	public final void setPaymentMethod(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.PaymentMethod paymentmethod)
	{
		if (paymentmethod != null) {
			getMendixObject().setValue(context, MemberNames.PaymentMethod.toString(), paymentmethod.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.PaymentMethod.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_User
	 */
	public final myfirstmodule.proxies.User getOrder_User() throws com.mendix.core.CoreException
	{
		return getOrder_User(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_User
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.User getOrder_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_User.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_User
	 * @param order_user
	 */
	public final void setOrder_User(myfirstmodule.proxies.User order_user)
	{
		setOrder_User(getContext(), order_user);
	}

	/**
	 * Set value of Order_User
	 * @param context
	 * @param order_user
	 */
	public final void setOrder_User(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.User order_user)
	{
		if (order_user == null) {
			getMendixObject().setValue(context, MemberNames.Order_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_User.toString(), order_user.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Order_RestaurantAPI
	 */
	public final myfirstmodule.proxies.RestaurantAPI getOrder_RestaurantAPI() throws com.mendix.core.CoreException
	{
		return getOrder_RestaurantAPI(getContext());
	}

	/**
	 * @param context
	 * @return value of Order_RestaurantAPI
	 * @throws com.mendix.core.CoreException
	 */
	public final myfirstmodule.proxies.RestaurantAPI getOrder_RestaurantAPI(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		myfirstmodule.proxies.RestaurantAPI result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Order_RestaurantAPI.toString());
		if (identifier != null) {
			result = myfirstmodule.proxies.RestaurantAPI.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Order_RestaurantAPI
	 * @param order_restaurantapi
	 */
	public final void setOrder_RestaurantAPI(myfirstmodule.proxies.RestaurantAPI order_restaurantapi)
	{
		setOrder_RestaurantAPI(getContext(), order_restaurantapi);
	}

	/**
	 * Set value of Order_RestaurantAPI
	 * @param context
	 * @param order_restaurantapi
	 */
	public final void setOrder_RestaurantAPI(com.mendix.systemwideinterfaces.core.IContext context, myfirstmodule.proxies.RestaurantAPI order_restaurantapi)
	{
		if (order_restaurantapi == null) {
			getMendixObject().setValue(context, MemberNames.Order_RestaurantAPI.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Order_RestaurantAPI.toString(), order_restaurantapi.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return orderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.Order that = (myfirstmodule.proxies.Order) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
