// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public enum OrderStatus
{
	Pending("000cac28-8107-4028-832e-633e46ca3cdd"),
	Confirmed("7735f7ba-17e3-4c6d-be6d-8300ad650b33"),
	Preparing("0a99bfd0-d3b7-4cac-8fe4-55ebcb704689"),
	OnTheWay("7c947e58-aed7-4c83-995a-f7f664f0bef5"),
	Delivered("4f20790e-12bf-4fe4-b2f3-c7902047d793"),
	Cancelled("7867d83b-f0b3-4b2a-ae2e-6ecf9a7520f8"),
	Cart("3a1a8af1-b2d4-4898-89d3-440920f997a5");

	private final java.lang.String i18nCaptionKey;
	
	private OrderStatus(java.lang.String i18nCaptionKey)
	{
		this.i18nCaptionKey = i18nCaptionKey;
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		String caption = com.mendix.core.Core.getInternationalizedString(languageCode, i18nCaptionKey);
		return caption.isEmpty() ? getCaption() : caption;
	}

	public java.lang.String getCaption()
	{
		return com.mendix.core.Core.getInternationalizedString("en_US", i18nCaptionKey);
	}
}
