// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class RestaurantAPI implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject restaurantAPIMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.RestaurantAPI";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		name("name"),
		address("address"),
		phone("phone"),
		email("email"),
		description("description"),
		workingHours("workingHours"),
		acceptsOrders("acceptsOrders"),
		unavailableReason("unavailableReason"),
		status("status"),
		restaurantId("restaurantId"),
		category("category"),
		rating("rating"),
		recommendationReason("recommendationReason"),
		recommendationScore("recommendationScore"),
		isRecommended("isRecommended");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public RestaurantAPI(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected RestaurantAPI(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject restaurantAPIMendixObject)
	{
		if (restaurantAPIMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!restaurantAPIMendixObject.isInstanceOf(entityName)) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.restaurantAPIMendixObject = restaurantAPIMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static myfirstmodule.proxies.RestaurantAPI initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.RestaurantAPI(context, mendixObject);
	}

	public static myfirstmodule.proxies.RestaurantAPI load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.RestaurantAPI.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.RestaurantAPI> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> myfirstmodule.proxies.RestaurantAPI.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of name
	 */
	public final java.lang.String getname()
	{
		return getname(getContext());
	}

	/**
	 * @param context
	 * @return value of name
	 */
	public final java.lang.String getname(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.name.toString());
	}

	/**
	 * Set value of name
	 * @param name
	 */
	public final void setname(java.lang.String name)
	{
		setname(getContext(), name);
	}

	/**
	 * Set value of name
	 * @param context
	 * @param name
	 */
	public final void setname(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.name.toString(), name);
	}

	/**
	 * @return value of address
	 */
	public final java.lang.String getaddress()
	{
		return getaddress(getContext());
	}

	/**
	 * @param context
	 * @return value of address
	 */
	public final java.lang.String getaddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.address.toString());
	}

	/**
	 * Set value of address
	 * @param address
	 */
	public final void setaddress(java.lang.String address)
	{
		setaddress(getContext(), address);
	}

	/**
	 * Set value of address
	 * @param context
	 * @param address
	 */
	public final void setaddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.address.toString(), address);
	}

	/**
	 * @return value of phone
	 */
	public final java.lang.String getphone()
	{
		return getphone(getContext());
	}

	/**
	 * @param context
	 * @return value of phone
	 */
	public final java.lang.String getphone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.phone.toString());
	}

	/**
	 * Set value of phone
	 * @param phone
	 */
	public final void setphone(java.lang.String phone)
	{
		setphone(getContext(), phone);
	}

	/**
	 * Set value of phone
	 * @param context
	 * @param phone
	 */
	public final void setphone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phone)
	{
		getMendixObject().setValue(context, MemberNames.phone.toString(), phone);
	}

	/**
	 * @return value of email
	 */
	public final java.lang.String getemail()
	{
		return getemail(getContext());
	}

	/**
	 * @param context
	 * @return value of email
	 */
	public final java.lang.String getemail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.email.toString());
	}

	/**
	 * Set value of email
	 * @param email
	 */
	public final void setemail(java.lang.String email)
	{
		setemail(getContext(), email);
	}

	/**
	 * Set value of email
	 * @param context
	 * @param email
	 */
	public final void setemail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.email.toString(), email);
	}

	/**
	 * @return value of description
	 */
	public final java.lang.String getdescription()
	{
		return getdescription(getContext());
	}

	/**
	 * @param context
	 * @return value of description
	 */
	public final java.lang.String getdescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.description.toString());
	}

	/**
	 * Set value of description
	 * @param description
	 */
	public final void setdescription(java.lang.String description)
	{
		setdescription(getContext(), description);
	}

	/**
	 * Set value of description
	 * @param context
	 * @param description
	 */
	public final void setdescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.description.toString(), description);
	}

	/**
	 * @return value of workingHours
	 */
	public final java.lang.String getworkingHours()
	{
		return getworkingHours(getContext());
	}

	/**
	 * @param context
	 * @return value of workingHours
	 */
	public final java.lang.String getworkingHours(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.workingHours.toString());
	}

	/**
	 * Set value of workingHours
	 * @param workinghours
	 */
	public final void setworkingHours(java.lang.String workinghours)
	{
		setworkingHours(getContext(), workinghours);
	}

	/**
	 * Set value of workingHours
	 * @param context
	 * @param workinghours
	 */
	public final void setworkingHours(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workinghours)
	{
		getMendixObject().setValue(context, MemberNames.workingHours.toString(), workinghours);
	}

	/**
	 * @return value of acceptsOrders
	 */
	public final java.lang.Boolean getacceptsOrders()
	{
		return getacceptsOrders(getContext());
	}

	/**
	 * @param context
	 * @return value of acceptsOrders
	 */
	public final java.lang.Boolean getacceptsOrders(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.acceptsOrders.toString());
	}

	/**
	 * Set value of acceptsOrders
	 * @param acceptsorders
	 */
	public final void setacceptsOrders(java.lang.Boolean acceptsorders)
	{
		setacceptsOrders(getContext(), acceptsorders);
	}

	/**
	 * Set value of acceptsOrders
	 * @param context
	 * @param acceptsorders
	 */
	public final void setacceptsOrders(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean acceptsorders)
	{
		getMendixObject().setValue(context, MemberNames.acceptsOrders.toString(), acceptsorders);
	}

	/**
	 * @return value of unavailableReason
	 */
	public final java.lang.String getunavailableReason()
	{
		return getunavailableReason(getContext());
	}

	/**
	 * @param context
	 * @return value of unavailableReason
	 */
	public final java.lang.String getunavailableReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.unavailableReason.toString());
	}

	/**
	 * Set value of unavailableReason
	 * @param unavailablereason
	 */
	public final void setunavailableReason(java.lang.String unavailablereason)
	{
		setunavailableReason(getContext(), unavailablereason);
	}

	/**
	 * Set value of unavailableReason
	 * @param context
	 * @param unavailablereason
	 */
	public final void setunavailableReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String unavailablereason)
	{
		getMendixObject().setValue(context, MemberNames.unavailableReason.toString(), unavailablereason);
	}

	/**
	 * @return value of status
	 */
	public final java.lang.String getstatus()
	{
		return getstatus(getContext());
	}

	/**
	 * @param context
	 * @return value of status
	 */
	public final java.lang.String getstatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.status.toString());
	}

	/**
	 * Set value of status
	 * @param status
	 */
	public final void setstatus(java.lang.String status)
	{
		setstatus(getContext(), status);
	}

	/**
	 * Set value of status
	 * @param context
	 * @param status
	 */
	public final void setstatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String status)
	{
		getMendixObject().setValue(context, MemberNames.status.toString(), status);
	}

	/**
	 * @return value of restaurantId
	 */
	public final java.lang.String getrestaurantId()
	{
		return getrestaurantId(getContext());
	}

	/**
	 * @param context
	 * @return value of restaurantId
	 */
	public final java.lang.String getrestaurantId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.restaurantId.toString());
	}

	/**
	 * Set value of restaurantId
	 * @param restaurantid
	 */
	public final void setrestaurantId(java.lang.String restaurantid)
	{
		setrestaurantId(getContext(), restaurantid);
	}

	/**
	 * Set value of restaurantId
	 * @param context
	 * @param restaurantid
	 */
	public final void setrestaurantId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String restaurantid)
	{
		getMendixObject().setValue(context, MemberNames.restaurantId.toString(), restaurantid);
	}

	/**
	 * @return value of category
	 */
	public final java.lang.String getcategory()
	{
		return getcategory(getContext());
	}

	/**
	 * @param context
	 * @return value of category
	 */
	public final java.lang.String getcategory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.category.toString());
	}

	/**
	 * Set value of category
	 * @param category
	 */
	public final void setcategory(java.lang.String category)
	{
		setcategory(getContext(), category);
	}

	/**
	 * Set value of category
	 * @param context
	 * @param category
	 */
	public final void setcategory(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String category)
	{
		getMendixObject().setValue(context, MemberNames.category.toString(), category);
	}

	/**
	 * @return value of rating
	 */
	public final java.math.BigDecimal getrating()
	{
		return getrating(getContext());
	}

	/**
	 * @param context
	 * @return value of rating
	 */
	public final java.math.BigDecimal getrating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.rating.toString());
	}

	/**
	 * Set value of rating
	 * @param rating
	 */
	public final void setrating(java.math.BigDecimal rating)
	{
		setrating(getContext(), rating);
	}

	/**
	 * Set value of rating
	 * @param context
	 * @param rating
	 */
	public final void setrating(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rating)
	{
		getMendixObject().setValue(context, MemberNames.rating.toString(), rating);
	}

	/**
	 * @return value of recommendationReason
	 */
	public final java.lang.String getrecommendationReason()
	{
		return getrecommendationReason(getContext());
	}

	/**
	 * @param context
	 * @return value of recommendationReason
	 */
	public final java.lang.String getrecommendationReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.recommendationReason.toString());
	}

	/**
	 * Set value of recommendationReason
	 * @param recommendationreason
	 */
	public final void setrecommendationReason(java.lang.String recommendationreason)
	{
		setrecommendationReason(getContext(), recommendationreason);
	}

	/**
	 * Set value of recommendationReason
	 * @param context
	 * @param recommendationreason
	 */
	public final void setrecommendationReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String recommendationreason)
	{
		getMendixObject().setValue(context, MemberNames.recommendationReason.toString(), recommendationreason);
	}

	/**
	 * @return value of recommendationScore
	 */
	public final java.math.BigDecimal getrecommendationScore()
	{
		return getrecommendationScore(getContext());
	}

	/**
	 * @param context
	 * @return value of recommendationScore
	 */
	public final java.math.BigDecimal getrecommendationScore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.recommendationScore.toString());
	}

	/**
	 * Set value of recommendationScore
	 * @param recommendationscore
	 */
	public final void setrecommendationScore(java.math.BigDecimal recommendationscore)
	{
		setrecommendationScore(getContext(), recommendationscore);
	}

	/**
	 * Set value of recommendationScore
	 * @param context
	 * @param recommendationscore
	 */
	public final void setrecommendationScore(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal recommendationscore)
	{
		getMendixObject().setValue(context, MemberNames.recommendationScore.toString(), recommendationscore);
	}

	/**
	 * @return value of isRecommended
	 */
	public final java.lang.Boolean getisRecommended()
	{
		return getisRecommended(getContext());
	}

	/**
	 * @param context
	 * @return value of isRecommended
	 */
	public final java.lang.Boolean getisRecommended(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isRecommended.toString());
	}

	/**
	 * Set value of isRecommended
	 * @param isrecommended
	 */
	public final void setisRecommended(java.lang.Boolean isrecommended)
	{
		setisRecommended(getContext(), isrecommended);
	}

	/**
	 * Set value of isRecommended
	 * @param context
	 * @param isrecommended
	 */
	public final void setisRecommended(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isrecommended)
	{
		getMendixObject().setValue(context, MemberNames.isRecommended.toString(), isrecommended);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return restaurantAPIMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.RestaurantAPI that = (myfirstmodule.proxies.RestaurantAPI) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
