// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyFirstModule module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AddToCartBuilder(
		myfirstmodule.proxies.ItemAPI _itemAPI
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_AddToCart");
		builder = builder.withParam("ItemAPI", _itemAPI);
		return builder;
	}

	public static void aCT_AddToCart(
		IContext context,
		myfirstmodule.proxies.ItemAPI _itemAPI
	)
	{
		aCT_AddToCartBuilder(
				_itemAPI
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_ConfirmOrderBuilder(
		myfirstmodule.proxies.Order _order
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.ACT_ConfirmOrder");
		builder = builder.withParam("Order", _order);
		return builder;
	}

	public static void aCT_ConfirmOrder(
		IContext context,
		myfirstmodule.proxies.Order _order
	)
	{
		aCT_ConfirmOrderBuilder(
				_order
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_GetRestaurants2Builder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MF_GetRestaurants2");
		return builder;
	}

	public static java.util.List<myfirstmodule.proxies.RestaurantAPI> mF_GetRestaurants2(IContext context)
	{
		Object result = mF_GetRestaurants2Builder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> myfirstmodule.proxies.RestaurantAPI.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder mF_OpenCartBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MF_OpenCart");
		return builder;
	}

	public static void mF_OpenCart(IContext context)
	{
		mF_OpenCartBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder myFirstLogicBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyFirstModule.MyFirstLogic");
		return builder;
	}

	public static void myFirstLogic(IContext context)
	{
		myFirstLogicBuilder().execute(context);
	}
}
